name: labmino_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Core
  http: ^1.2.2
  get: ^4.6.5
  provider: ^6.1.1
  get_it: ^8.0.2
  pbp_django_auth: ^0.4.0
  url_launcher: ^6.0.6
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  rename: ^3.0.2

  # UI & Animation
  google_fonts: ^6.3.1
  lottie: ^3.3.2
  carousel_slider: ^5.1.1

  # Media & Image
  image_picker: ^1.2.0
  intl: ^0.20.2
  flutter_tts: ^4.0.2

  # Grouping & Lists
  grouped_list: ^5.1.2

  # Splash & Icons
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
